// Service Worker for StoryShare PWA
// Handles: Push Notifications + Offline Caching via Workbox

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Precache all assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// ─── Caching Strategies ───────────────────────────────────────────────────────

// API calls: NetworkFirst - dynamic data still appears offline
registerRoute(
  ({ url }) => url.origin === 'https://story-api.dicoding.dev',
  new NetworkFirst({
    cacheName: 'story-api-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 }), // 24h
    ],
  })
);

// Google Fonts: CacheFirst
registerRoute(
  ({ url }) =>
    url.origin === 'https://fonts.googleapis.com' ||
    url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 }),
    ],
  })
);

// Story images from API: StaleWhileRevalidate
registerRoute(
  ({ url }) =>
    url.hostname.includes('story-api.dicoding.dev') &&
    url.pathname.match(/\.(jpg|jpeg|png|gif|webp)$/i),
  new StaleWhileRevalidate({
    cacheName: 'story-images-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 60 * 60 * 24 * 7 }), // 7 days
    ],
  })
);

// Leaflet tiles: CacheFirst
registerRoute(
  ({ url }) =>
    url.hostname.includes('tile.openstreetmap.org') ||
    url.hostname.includes('arcgisonline.com') ||
    url.hostname.includes('unpkg.com'),
  new CacheFirst({
    cacheName: 'map-tiles-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 500, maxAgeSeconds: 60 * 60 * 24 * 30 }),
    ],
  })
);

// ─── Push Notification Handler ────────────────────────────────────────────────

self.addEventListener('push', (event) => {
  let notificationTitle = 'StoryShare';
  let notificationOptions = {
    body: 'Ada cerita baru yang menunggu Anda!',
    icon: '/icons/app_icon_512_1789821112827.jpg',
    badge: '/icons/app_icon_512_1789821112827.jpg',
    vibrate: [100, 50, 100],
    data: { url: '/' },
    actions: [
      { action: 'view', title: '👁️ Lihat Cerita' },
      { action: 'close', title: '✕ Tutup' },
    ],
  };

  if (event.data) {
    try {
      const data = event.data.json();

      notificationTitle = data.title || 'StoryShare - Story Baru!';
      notificationOptions = {
        ...notificationOptions,
        body: data.options?.body || data.body || 'Ada cerita baru yang ditambahkan!',
        icon: data.options?.icon || notificationOptions.icon,
        image: data.options?.image || null,
        tag: data.options?.tag || 'story-notification',
        data: {
          url:
            data.options?.data?.url ||
            (data.storyId ? `/#/stories/${data.storyId}` : '/'),
          storyId: data.storyId || null,
        },
      };
    } catch (_e) {
      notificationOptions.body = event.data.text();
    }
  }

  event.waitUntil(
    self.registration.showNotification(notificationTitle, notificationOptions)
  );
});

// ─── Notification Click Handler ───────────────────────────────────────────────

self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  if (event.action === 'close') return;

  const targetUrl =
    event.notification.data && event.notification.data.url
      ? event.notification.data.url
      : '/';

  event.waitUntil(
    clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        for (const client of clientList) {
          if ('focus' in client) {
            client.navigate(targetUrl);
            return client.focus();
          }
        }
        if (clients.openWindow) {
          return clients.openWindow(targetUrl);
        }
      })
  );
});
